/* tslint:disable */
import { PromotionResult } from './promotion-result';
import { Voucher } from './voucher';
import { Consignment } from './consignment';
import { Address } from './address';
import { Price } from './price';
import { DeliveryMode } from './delivery-mode';
import { DeliveryOrderEntryGroup } from './delivery-order-entry-group';
import { OrderEntry } from './order-entry';
import { PaymentDetails } from './payment-details';
import { PickupOrderEntryGroup } from './pickup-order-entry-group';
import { Principal } from './principal';
export interface Order {
  net?: boolean;
  appliedOrderPromotions?: Array<PromotionResult>;
  appliedVouchers?: Array<Voucher>;
  calculated?: boolean;
  code?: string;
  consignments?: Array<Consignment>;
  created?: string;
  deliveryAddress?: Address;
  deliveryCost?: Price;
  deliveryItemsQuantity?: number;
  deliveryMode?: DeliveryMode;
  deliveryOrderGroups?: Array<DeliveryOrderEntryGroup>;
  deliveryStatus?: string;
  deliveryStatusDisplay?: string;
  entries?: Array<OrderEntry>;
  guestCustomer?: boolean;
  guid?: string;
  appliedProductPromotions?: Array<PromotionResult>;
  orderDiscounts?: Price;
  paymentInfo?: PaymentDetails;
  pickupItemsQuantity?: number;
  pickupOrderGroups?: Array<PickupOrderEntryGroup>;
  productDiscounts?: Price;
  site?: string;
  status?: string;
  statusDisplay?: string;
  store?: string;
  subTotal?: Price;
  totalDiscounts?: Price;
  totalItems?: number;
  totalPrice?: Price;
  totalPriceWithTax?: Price;
  totalTax?: Price;
  unconsignedEntries?: Array<OrderEntry>;
  user?: Principal;
}
